version: "3.9"

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest
    restart: unless-stopped
    hostname: adguard
    # Volumes store your data between container upgrades
    volumes:
      - "./adguard-workdir:/opt/adguardhome/work"
      - "./adguard-confdir:/opt/adguardhome/conf"
    ports:
      - 3100:3000/tcp
    networks:
      private_network:
        ipv4_address: 10.2.0.100
  wireguard:
    depends_on: [adguard]
    image: linuxserver/wireguard:latest
    restart: unless-stopped
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London # Change to your timezone
      - SERVERPORT=51830
      #- SERVERURL=my.ddns.net #optional - For use with DDNS (Uncomment to use)
      - PEERS=5 # How many peers to generate for you (clients)
      - PEERDNS=10.2.0.100 # Set it to point to adguard home
      - INTERNAL_SUBNET=10.0.0.0
      - ALLOWEDIPS=0.0.0.0/0,192.168.100.0/24 # optional - split tunnel for web panel and DNS traffic only
    ports:
      - 51830:51830/udp
    volumes:
      - ./wireguard-config:/config
      - ./wireguard-modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      private_network:
        ipv4_address: 10.2.0.3
    
